import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': 'rgb(var(--surface-container-high) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--on-primary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--on-secondary-container) / <alpha-value>)',
        'error-container': 'rgb(var(--error-container) / <alpha-value>)',
        'surface-bright': 'rgb(var(--surface-container-lowest) / <alpha-value>)',
        'primary-fixed': '#dbe1ff',
        'on-secondary-fixed-variant': '#005236',
        'surface-container': 'rgb(var(--surface-container) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant) / <alpha-value>)',
        'secondary-fixed': '#6ffbbe',
        primary: 'rgb(var(--primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--primary-container) / <alpha-value>)',
        'outline-variant': 'rgb(var(--outline-variant) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface-container-highest) / <alpha-value>)',
        'on-error': 'rgb(var(--on-surface) / <alpha-value>)',
        'secondary-container': 'rgb(var(--secondary-container) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--tertiary-container) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'primary-fixed-dim': '#b4c5ff',
        'on-tertiary-container': 'rgb(var(--on-tertiary-container) / <alpha-value>)',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-fixed-variant': '#003ea8',
        background: 'rgb(var(--background) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface) / <alpha-value>)',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#0053db',
        error: 'rgb(var(--error) / <alpha-value>)',
        outline: 'rgb(var(--outline) / <alpha-value>)',
        'tertiary-fixed-dim': '#ffb95f',
        'tertiary-fixed': '#ffddb8',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest) / <alpha-value>)',
        'on-tertiary': '#472a00',
        'on-background': 'rgb(var(--on-surface) / <alpha-value>)',
        'surface-variant': 'rgb(var(--surface-container-high) / <alpha-value>)',
        secondary: 'rgb(var(--secondary) / <alpha-value>)',
        'on-secondary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-container-high': 'rgb(var(--surface-container-high) / <alpha-value>)',
        tertiary: 'rgb(var(--tertiary) / <alpha-value>)',
        'on-secondary': '#003824',
        'surface-container-low': 'rgb(var(--surface-container) / <alpha-value>)',
        'surface-tint': 'rgb(var(--primary) / <alpha-value>)',
        'on-tertiary-fixed': '#2a1700',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#00174b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '1rem',
        'stack-lg': '1.5rem',
        'stack-xs': '0.25rem',
        'margin-page': '2rem',
        'stack-sm': '0.5rem',
        gutter: '1.5rem',
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-md': ['var(--font-inter)', 'sans-serif'],
        'mono-data': ['var(--font-jetbrains-mono)', 'monospace'],
        'headline-sm': ['var(--font-inter)', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'sans-serif'],
        'label-sm': ['var(--font-inter)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'label-md': ['var(--font-inter)', 'sans-serif'],
        'display-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'mono-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

export default config
